// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZVuMeUxrWf2MStwBonRwvifvWOt5snkM',
    appId: '1:640695861238:web:628b4a8831fc618925d1d7',
    messagingSenderId: '640695861238',
    projectId: 'fasomatch',
    authDomain: 'fasomatch.firebaseapp.com',
    storageBucket: 'fasomatch.firebasestorage.app',
    measurementId: 'G-2MTQQV8SVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF5puPraCl9liKaeyn0JTIFVJw1H2uN8o',
    appId: '1:640695861238:android:c24f10e0b6ca9be225d1d7',
    messagingSenderId: '640695861238',
    projectId: 'fasomatch',
    storageBucket: 'fasomatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQRuCdHR2jbrXImYjEWNmORrq9zSlHzmY',
    appId: '1:640695861238:ios:929643155a7de15a25d1d7',
    messagingSenderId: '640695861238',
    projectId: 'fasomatch',
    storageBucket: 'fasomatch.firebasestorage.app',
    iosBundleId: 'com.example.fasomatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQRuCdHR2jbrXImYjEWNmORrq9zSlHzmY',
    appId: '1:640695861238:ios:929643155a7de15a25d1d7',
    messagingSenderId: '640695861238',
    projectId: 'fasomatch',
    storageBucket: 'fasomatch.firebasestorage.app',
    iosBundleId: 'com.example.fasomatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZVuMeUxrWf2MStwBonRwvifvWOt5snkM',
    appId: '1:640695861238:web:ae15464506b532c025d1d7',
    messagingSenderId: '640695861238',
    projectId: 'fasomatch',
    authDomain: 'fasomatch.firebaseapp.com',
    storageBucket: 'fasomatch.firebasestorage.app',
    measurementId: 'G-F6SMPHKR8Z',
  );
}
